import { GlobalStyle, Text } from '@chakra-ui/react'
import Head from 'next/head'
import styles from 'shared/styles/Home.module.css'
//import GlobalStyles from 'shared/styles/global' 

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portal do Desenvolvedor</title>
        <meta name="description" content="Generated by create next app" /> 
      </Head>

      <main className={styles.main}>
        <Text
        fontSize="27px"
        color="#fff000"
        >
          Drivers
        </Text>
        {/* <GlobalStyles /> */}
      </main>
    </div>
  )
}